
CREATE TABLE code_uris (
  vocab varchar NOT NULL,
  code varchar NOT NULL,
  uri varchar NOT NULL,
  prefLabel varchar NOT NULL,
  PRIMARY KEY(vocab, code)
);

INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('GnafConfidenceIndividuals.ttl', '0', 'http://gnafld.net/def/gnaf/GnafConfidence_0', 'Confidence level 0');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('GnafConfidenceIndividuals.ttl', '2', 'http://gnafld.net/def/gnaf/GnafConfidence_2', 'Confidence level 2');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('GnafConfidenceIndividuals.ttl', '1', 'http://gnafld.net/def/gnaf/GnafConfidence_1', 'Confidence level 1');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('GnafConfidenceIndividuals.ttl', '-1', 'http://gnafld.net/def/gnaf/GnafConfidence_-1', 'Confidence level -1');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('GeocodeReliabilityIndividuals.ttl', '6', 'http://gnafld.net/def/gnaf/UniqueRegion', 'Unique Region');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('GeocodeReliabilityIndividuals.ttl', '3', 'http://gnafld.net/def/gnaf/NearOrPossiblyWithinAddressSiteBoundary', 'Near (Or Possibly Within) Address Site Boundary');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('GeocodeReliabilityIndividuals.ttl', '5', 'http://gnafld.net/def/gnaf/UniqueLocalityOrNeighbourhood', 'Unique Locality Or Neighbourhood');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('GeocodeReliabilityIndividuals.ttl', '4', 'http://gnafld.net/def/gnaf/UniqueRoadFeature', 'Unique Road Feature');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('GeocodeReliabilityIndividuals.ttl', '2', 'http://gnafld.net/def/gnaf/WithinAddressSiteBoundaryOrAccessPoint', 'Within Address Site Boundary or Access Point');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('GeocodeReliabilityIndividuals.ttl', '1', 'http://gnafld.net/def/gnaf/SurveyingStandard', 'Surveying Standard');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StateIndividuals.ttl', 'SA', 'http://www.geonames.org/2061327', 'South Australia');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StateIndividuals.ttl', 'TAS', 'http://www.geonames.org/2147291', 'Tasmania');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StateIndividuals.ttl', 'VIC', 'http://www.geonames.org/2145234', 'Victoria');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StateIndividuals.ttl', 'OT', 'http://gnafld.net/def/gnaf/State/OT', 'Other Territories');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StateIndividuals.ttl', 'ACT', 'http://www.geonames.org/2177478', 'Australian Capital Territory');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StateIndividuals.ttl', 'NT', 'http://www.geonames.org/2064513', 'Northern Territory');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StateIndividuals.ttl', 'WA', 'http://www.geonames.org/2058645', 'Western Australia');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StateIndividuals.ttl', 'QLD', 'http://www.geonames.org/2152274', 'Queensland');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StateIndividuals.ttl', 'NSW', 'http://www.geonames.org/2155400', 'New South Wales');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetConfirmationIndividuals.ttl', 'CONFIRMED', 'http://gnafld.net/def/gnaf/StreetConfirmation/Confirmed', 'Confirmed');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetConfirmationIndividuals.ttl', 'UNCONFIRMED', 'http://gnafld.net/def/gnaf/StreetConfirmation/Unconfirmed', 'Unconfirmed');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'CENTRAL', 'http://gnafld.net/def/gnaf/StreetSuffix/CN', 'Central');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'EXTENSION', 'http://gnafld.net/def/gnaf/StreetSuffix/EX', 'Extension');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'OFF', 'http://gnafld.net/def/gnaf/StreetSuffix/OF', 'Off');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'NORTH WEST', 'http://gnafld.net/def/gnaf/StreetSuffix/NW', 'North West');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'DEVIATION', 'http://gnafld.net/def/gnaf/StreetSuffix/DE', 'Deviation');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'UPPER', 'http://gnafld.net/def/gnaf/StreetSuffix/UP', 'Upper');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'OUTER', 'http://gnafld.net/def/gnaf/StreetSuffix/OT', 'Outer');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'SOUTH WEST', 'http://gnafld.net/def/gnaf/StreetSuffix/SW', 'South West');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'SOUTH EAST', 'http://gnafld.net/def/gnaf/StreetSuffix/SE', 'South East');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'LOWER', 'http://gnafld.net/def/gnaf/StreetSuffix/LR', 'Lower');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'MALL', 'http://gnafld.net/def/gnaf/StreetSuffix/ML', 'Mall');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'ON', 'http://gnafld.net/def/gnaf/StreetSuffix/ON', 'On');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'EAST', 'http://gnafld.net/def/gnaf/StreetSuffix/E', 'East');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'SOUTH', 'http://gnafld.net/def/gnaf/StreetSuffix/S', 'South');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'NORTH', 'http://gnafld.net/def/gnaf/StreetSuffix/N', 'North');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'INNER', 'http://gnafld.net/def/gnaf/StreetSuffix/IN', 'Inner');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'NORTH EAST', 'http://gnafld.net/def/gnaf/StreetSuffix/NE', 'North East');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'OVERPASS', 'http://gnafld.net/def/gnaf/StreetSuffix/OP', 'Overpass');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('StreetSuffixIndividuals.ttl', 'WEST', 'http://gnafld.net/def/gnaf/StreetSuffix/W', 'West');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Locality', 'V', 'http://gnafld.net/def/gnaf#UnofficialTopographicFeatureLocality', 'Unofficial Topographic Feature');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Locality', 'A', 'http://gnafld.net/def/gnaf#AliasOnlyLocality', 'Alias Only Locality');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Locality', 'T', 'http://gnafld.net/def/gnaf#TopographicLocality', 'Topographic Locality');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Locality', 'U', 'http://gnafld.net/def/gnaf#UnofficialSuburbLocality', 'Unofficial Suburb');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Locality', 'H', 'http://gnafld.net/def/gnaf#HundredLocality', 'Hundred');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Locality', 'D', 'http://gnafld.net/def/gnaf#DistrictLocality', 'District');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Locality', 'G', 'http://gnafld.net/def/gnaf#GazetedLocality', 'Gazeted Locality');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Locality', 'M', 'http://gnafld.net/def/gnaf#ManuallyValidatedLocality', 'Manually Validated');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WAY', 'http://gnafld.net/def/gnaf#WayStreet', 'Way');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BSWY', 'http://gnafld.net/def/gnaf#BuswayStreet', 'Busway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BUSWAY', 'http://gnafld.net/def/gnaf#BuswayStreet', 'Busway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CTYD', 'http://gnafld.net/def/gnaf#CourtyardStreet', 'Courtyard');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'COURTYARD', 'http://gnafld.net/def/gnaf#CourtyardStreet', 'Courtyard');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RUN', 'http://gnafld.net/def/gnaf#RunStreet', 'Run');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GLDE', 'http://gnafld.net/def/gnaf#GladeStreet', 'Glade');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GLADE', 'http://gnafld.net/def/gnaf#GladeStreet', 'Glade');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'QY', 'http://gnafld.net/def/gnaf#QuayStreet', 'Quay');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'QUAY', 'http://gnafld.net/def/gnaf#QuayStreet', 'Quay');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'OVAL', 'http://gnafld.net/def/gnaf#OvalStreet', 'Oval');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GTE', 'http://gnafld.net/def/gnaf#GateStreet', 'Gate');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GATE', 'http://gnafld.net/def/gnaf#GateStreet', 'Gate');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CNR', 'http://gnafld.net/def/gnaf#CornerStreet', 'Corner');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CORNER', 'http://gnafld.net/def/gnaf#CornerStreet', 'Corner');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'KNOL', 'http://gnafld.net/def/gnaf#KnollStreet', 'Knoll');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'KNOLL', 'http://gnafld.net/def/gnaf#KnollStreet', 'Knoll');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CORSO', 'http://gnafld.net/def/gnaf#CorsoStreet', 'Corso');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CSO', 'http://gnafld.net/def/gnaf#CorsoStreet', 'Corso');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LEAD', 'http://gnafld.net/def/gnaf#LeadStreet', 'Lead');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ELB', 'http://gnafld.net/def/gnaf#ElbowStreet', 'Elbow');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ELBOW', 'http://gnafld.net/def/gnaf#ElbowStreet', 'Elbow');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HILL', 'http://gnafld.net/def/gnaf#HillStreet', 'Hill');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ACRE', 'http://gnafld.net/def/gnaf#AcreStreet', 'Acre');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ACRE', 'http://gnafld.net/def/gnaf#AcreStreet', 'Acre');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ESMT', 'http://gnafld.net/def/gnaf#EasementStreet', 'Easement');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'EASEMENT', 'http://gnafld.net/def/gnaf#EasementStreet', 'Easement');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RUE', 'http://gnafld.net/def/gnaf#RueStreet', 'Rue');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DOWNS', 'http://gnafld.net/def/gnaf#DownsStreet', 'Downs');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DWNS', 'http://gnafld.net/def/gnaf#DownsStreet', 'Downs');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CROOK', 'http://gnafld.net/def/gnaf#CrookStreet', 'Crook');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CRK', 'http://gnafld.net/def/gnaf#CrookStreet', 'Crook');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CSAC', 'http://gnafld.net/def/gnaf#Cul-De-SacStreet', 'Cul-De-Sac');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CUL-DE-SAC', 'http://gnafld.net/def/gnaf#Cul-De-SacStreet', 'Cul-De-Sac');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BANAN', 'http://gnafld.net/def/gnaf#BananStreet', 'Banan');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BA', 'http://gnafld.net/def/gnaf#BananStreet', 'Banan');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'APP', 'http://gnafld.net/def/gnaf#ApproachStreet', 'Approach');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'APPROACH', 'http://gnafld.net/def/gnaf#ApproachStreet', 'Approach');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BOARDWALK', 'http://gnafld.net/def/gnaf#BoardwalkStreet', 'Boardwalk');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BWLK', 'http://gnafld.net/def/gnaf#BoardwalkStreet', 'Boardwalk');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'COLONNADE', 'http://gnafld.net/def/gnaf#ColonnadeStreet', 'Colonnade');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CLDE', 'http://gnafld.net/def/gnaf#ColonnadeStreet', 'Colonnade');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ROUND', 'http://gnafld.net/def/gnaf#RoundStreet', 'Round');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RND', 'http://gnafld.net/def/gnaf#RoundStreet', 'Round');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MART', 'http://gnafld.net/def/gnaf#MartStreet', 'Mart');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TWIST', 'http://gnafld.net/def/gnaf#TwistStreet', 'Twist');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TWIST', 'http://gnafld.net/def/gnaf#TwistStreet', 'Twist');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BYPA', 'http://gnafld.net/def/gnaf#BypassStreet', 'Bypass');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BYPASS', 'http://gnafld.net/def/gnaf#BypassStreet', 'Bypass');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GAP', 'http://gnafld.net/def/gnaf#GapStreet', 'Gap');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GROVE', 'http://gnafld.net/def/gnaf#GroveStreet', 'Grove');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GR', 'http://gnafld.net/def/gnaf#GroveStreet', 'Grove');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PLMS', 'http://gnafld.net/def/gnaf#PalmsStreet', 'Palms');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PALMS', 'http://gnafld.net/def/gnaf#PalmsStreet', 'Palms');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PART', 'http://gnafld.net/def/gnaf#PartStreet', 'Part');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BROW', 'http://gnafld.net/def/gnaf#BrowStreet', 'Brow');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DASH', 'http://gnafld.net/def/gnaf#DashStreet', 'Dash');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PRDS', 'http://gnafld.net/def/gnaf#ParadiseStreet', 'Paradise');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PARADISE', 'http://gnafld.net/def/gnaf#ParadiseStreet', 'Paradise');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SQUARE', 'http://gnafld.net/def/gnaf#SquareStreet', 'Square');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SQ', 'http://gnafld.net/def/gnaf#SquareStreet', 'Square');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BRET', 'http://gnafld.net/def/gnaf#BrettStreet', 'Brett');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BRETT', 'http://gnafld.net/def/gnaf#BrettStreet', 'Brett');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CONCOURSE', 'http://gnafld.net/def/gnaf#ConcourseStreet', 'Concourse');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CON', 'http://gnafld.net/def/gnaf#ConcourseStreet', 'Concourse');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TRAVERSE', 'http://gnafld.net/def/gnaf#TraverseStreet', 'Traverse');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TVSE', 'http://gnafld.net/def/gnaf#TraverseStreet', 'Traverse');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VILLAGE', 'http://gnafld.net/def/gnaf#VillageStreet', 'Village');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VLGE', 'http://gnafld.net/def/gnaf#VillageStreet', 'Village');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CH', 'http://gnafld.net/def/gnaf#ChaseStreet', 'Chase');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CHASE', 'http://gnafld.net/def/gnaf#ChaseStreet', 'Chase');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MALL', 'http://gnafld.net/def/gnaf#MallStreet', 'Mall');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PASS', 'http://gnafld.net/def/gnaf#PassStreet', 'Pass');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GARDEN', 'http://gnafld.net/def/gnaf#GardenStreet', 'Garden');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GDN', 'http://gnafld.net/def/gnaf#GardenStreet', 'Garden');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BAY', 'http://gnafld.net/def/gnaf#BayStreet', 'Bay');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PURSUIT', 'http://gnafld.net/def/gnaf#PursuitStreet', 'Pursuit');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PRST', 'http://gnafld.net/def/gnaf#PursuitStreet', 'Pursuit');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DR', 'http://gnafld.net/def/gnaf#DriveStreet', 'Drive');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DRIVE', 'http://gnafld.net/def/gnaf#DriveStreet', 'Drive');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PORT', 'http://gnafld.net/def/gnaf#PortStreet', 'Port');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'QDRT', 'http://gnafld.net/def/gnaf#QuadrantStreet', 'Quadrant');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'QUADRANT', 'http://gnafld.net/def/gnaf#QuadrantStreet', 'Quadrant');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VLLY', 'http://gnafld.net/def/gnaf#ValleyStreet', 'Valley');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VALLEY', 'http://gnafld.net/def/gnaf#ValleyStreet', 'Valley');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'REEF', 'http://gnafld.net/def/gnaf#ReefStreet', 'Reef');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VILLA', 'http://gnafld.net/def/gnaf#VillaStreet', 'Villa');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VLLA', 'http://gnafld.net/def/gnaf#VillaStreet', 'Villa');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PARADE', 'http://gnafld.net/def/gnaf#ParadeStreet', 'Parade');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PDE', 'http://gnafld.net/def/gnaf#ParadeStreet', 'Parade');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WYND', 'http://gnafld.net/def/gnaf#WyndStreet', 'Wynd');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WYND', 'http://gnafld.net/def/gnaf#WyndStreet', 'Wynd');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'POCKET', 'http://gnafld.net/def/gnaf#PocketStreet', 'Pocket');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PKT', 'http://gnafld.net/def/gnaf#PocketStreet', 'Pocket');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VALE', 'http://gnafld.net/def/gnaf#ValeStreet', 'Vale');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CR', 'http://gnafld.net/def/gnaf#CrescentStreet', 'Crescent');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CRESCENT', 'http://gnafld.net/def/gnaf#CrescentStreet', 'Crescent');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ALLY', 'http://gnafld.net/def/gnaf#AlleyStreet', 'Alley');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ALLEY', 'http://gnafld.net/def/gnaf#AlleyStreet', 'Alley');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RING', 'http://gnafld.net/def/gnaf#RingStreet', 'Ring');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ROTARY', 'http://gnafld.net/def/gnaf#RotaryStreet', 'Rotary');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RTY', 'http://gnafld.net/def/gnaf#RotaryStreet', 'Rotary');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VERGE', 'http://gnafld.net/def/gnaf#VergeStreet', 'Verge');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HILLS', 'http://gnafld.net/def/gnaf#HillsStreet', 'Hills');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BRAE', 'http://gnafld.net/def/gnaf#BraeStreet', 'Brae');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'COPSE', 'http://gnafld.net/def/gnaf#CopseStreet', 'Copse');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CPS', 'http://gnafld.net/def/gnaf#CopseStreet', 'Copse');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'OTLT', 'http://gnafld.net/def/gnaf#OutletStreet', 'Outlet');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'OUTLET', 'http://gnafld.net/def/gnaf#OutletStreet', 'Outlet');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LANE', 'http://gnafld.net/def/gnaf#LaneStreet', 'Lane');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SKYLINE', 'http://gnafld.net/def/gnaf#SkylineStreet', 'Skyline');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SKLN', 'http://gnafld.net/def/gnaf#SkylineStreet', 'Skyline');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BOULEVARD', 'http://gnafld.net/def/gnaf#BoulevardStreet', 'Boulevard');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BVD', 'http://gnafld.net/def/gnaf#BoulevardStreet', 'Boulevard');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SOUTH', 'http://gnafld.net/def/gnaf#SouthStreet', 'South');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'STH', 'http://gnafld.net/def/gnaf#SouthStreet', 'South');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GREEN', 'http://gnafld.net/def/gnaf#GreenStreet', 'Green');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GRN', 'http://gnafld.net/def/gnaf#GreenStreet', 'Green');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FOLW', 'http://gnafld.net/def/gnaf#FollowStreet', 'Follow');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FOLLOW', 'http://gnafld.net/def/gnaf#FollowStreet', 'Follow');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MEAD', 'http://gnafld.net/def/gnaf#MeadStreet', 'Mead');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TOR', 'http://gnafld.net/def/gnaf#TorStreet', 'Tor');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DELL', 'http://gnafld.net/def/gnaf#DellStreet', 'Dell');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'COMMON', 'http://gnafld.net/def/gnaf#CommonStreet', 'Common');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CMMN', 'http://gnafld.net/def/gnaf#CommonStreet', 'Common');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CRUISEWAY', 'http://gnafld.net/def/gnaf#CruisewayStreet', 'Cruiseway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CUWY', 'http://gnafld.net/def/gnaf#CruisewayStreet', 'Cruiseway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GRA', 'http://gnafld.net/def/gnaf#GrangeStreet', 'Grange');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GRANGE', 'http://gnafld.net/def/gnaf#GrangeStreet', 'Grange');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HTS', 'http://gnafld.net/def/gnaf#HeightsStreet', 'Heights');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HEIGHTS', 'http://gnafld.net/def/gnaf#HeightsStreet', 'Heights');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BRDWLK', 'http://gnafld.net/def/gnaf#BroadwalkStreet', 'Broadwalk');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BROADWALK', 'http://gnafld.net/def/gnaf#BroadwalkStreet', 'Broadwalk');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DOMAIN', 'http://gnafld.net/def/gnaf#DomainStreet', 'Domain');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DOM', 'http://gnafld.net/def/gnaf#DomainStreet', 'Domain');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MEANDER', 'http://gnafld.net/def/gnaf#MeanderStreet', 'Meander');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MNDR', 'http://gnafld.net/def/gnaf#MeanderStreet', 'Meander');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'NOOK', 'http://gnafld.net/def/gnaf#NookStreet', 'Nook');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ARTL', 'http://gnafld.net/def/gnaf#ArterialStreet', 'Arterial');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ARTERIAL', 'http://gnafld.net/def/gnaf#ArterialStreet', 'Arterial');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DOCK', 'http://gnafld.net/def/gnaf#DockStreet', 'Dock');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RNGE', 'http://gnafld.net/def/gnaf#RangeStreet', 'Range');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RANGE', 'http://gnafld.net/def/gnaf#RangeStreet', 'Range');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ESP', 'http://gnafld.net/def/gnaf#EsplanadeStreet', 'Esplanade');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ESPLANADE', 'http://gnafld.net/def/gnaf#EsplanadeStreet', 'Esplanade');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ROWE', 'http://gnafld.net/def/gnaf#RoweStreet', 'Rowe');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CUT', 'http://gnafld.net/def/gnaf#CutStreet', 'Cut');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HAVEN', 'http://gnafld.net/def/gnaf#HavenStreet', 'Haven');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HVN', 'http://gnafld.net/def/gnaf#HavenStreet', 'Haven');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CLOSE', 'http://gnafld.net/def/gnaf#CloseStreet', 'Close');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CL', 'http://gnafld.net/def/gnaf#CloseStreet', 'Close');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VSTA', 'http://gnafld.net/def/gnaf#VistaStreet', 'Vista');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VISTA', 'http://gnafld.net/def/gnaf#VistaStreet', 'Vista');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HOLLOW', 'http://gnafld.net/def/gnaf#HollowStreet', 'Hollow');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HLLW', 'http://gnafld.net/def/gnaf#HollowStreet', 'Hollow');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FITR', 'http://gnafld.net/def/gnaf#FiretrailStreet', 'Firetrail');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FIRETRAIL', 'http://gnafld.net/def/gnaf#FiretrailStreet', 'Firetrail');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'END', 'http://gnafld.net/def/gnaf#EndStreet', 'End');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'STAI', 'http://gnafld.net/def/gnaf#StraitStreet', 'Strait');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'STRAIT', 'http://gnafld.net/def/gnaf#StraitStreet', 'Strait');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WD', 'http://gnafld.net/def/gnaf#WoodStreet', 'Wood');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WOOD', 'http://gnafld.net/def/gnaf#WoodStreet', 'Wood');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ISLAND', 'http://gnafld.net/def/gnaf#IslandStreet', 'Island');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ID', 'http://gnafld.net/def/gnaf#IslandStreet', 'Island');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RD', 'http://gnafld.net/def/gnaf#RoadStreet', 'Road');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ROAD', 'http://gnafld.net/def/gnaf#RoadStreet', 'Road');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'COVE', 'http://gnafld.net/def/gnaf#CoveStreet', 'Cove');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VIEW', 'http://gnafld.net/def/gnaf#ViewStreet', 'View');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DRIVEWAY', 'http://gnafld.net/def/gnaf#DrivewayStreet', 'Driveway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DVWY', 'http://gnafld.net/def/gnaf#DrivewayStreet', 'Driveway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TURN', 'http://gnafld.net/def/gnaf#TurnStreet', 'Turn');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BOWL', 'http://gnafld.net/def/gnaf#BowlStreet', 'Bowl');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ARTERY', 'http://gnafld.net/def/gnaf#ArteryStreet', 'Artery');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ARTY', 'http://gnafld.net/def/gnaf#ArteryStreet', 'Artery');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LADR', 'http://gnafld.net/def/gnaf#LadderStreet', 'Ladder');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LADDER', 'http://gnafld.net/def/gnaf#LadderStreet', 'Ladder');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CUTT', 'http://gnafld.net/def/gnaf#CuttingStreet', 'Cutting');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CUTTING', 'http://gnafld.net/def/gnaf#CuttingStreet', 'Cutting');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RISE', 'http://gnafld.net/def/gnaf#RiseStreet', 'Rise');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RISE', 'http://gnafld.net/def/gnaf#RiseStreet', 'Rise');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LINK', 'http://gnafld.net/def/gnaf#LinkStreet', 'Link');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CRSS', 'http://gnafld.net/def/gnaf#CrossStreet', 'Cross');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CROSS', 'http://gnafld.net/def/gnaf#CrossStreet', 'Cross');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TRACK', 'http://gnafld.net/def/gnaf#TrackStreet', 'Track');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TRK', 'http://gnafld.net/def/gnaf#TrackStreet', 'Track');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ACCS', 'http://gnafld.net/def/gnaf#AccessStreet', 'Access');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ACCESS', 'http://gnafld.net/def/gnaf#AccessStreet', 'Access');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FREEWAY', 'http://gnafld.net/def/gnaf#FreewayStreet', 'Freeway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FWY', 'http://gnafld.net/def/gnaf#FreewayStreet', 'Freeway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BRAN', 'http://gnafld.net/def/gnaf#BranchStreet', 'Branch');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BRANCH', 'http://gnafld.net/def/gnaf#BranchStreet', 'Branch');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WKWY', 'http://gnafld.net/def/gnaf#WalkwayStreet', 'Walkway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WALKWAY', 'http://gnafld.net/def/gnaf#WalkwayStreet', 'Walkway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PSLA', 'http://gnafld.net/def/gnaf#PeninsulaStreet', 'Peninsula');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PENINSULA', 'http://gnafld.net/def/gnaf#PeninsulaStreet', 'Peninsula');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RTT', 'http://gnafld.net/def/gnaf#RetreatStreet', 'Retreat');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RETREAT', 'http://gnafld.net/def/gnaf#RetreatStreet', 'Retreat');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MTWY', 'http://gnafld.net/def/gnaf#MotorwayStreet', 'Motorway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MOTORWAY', 'http://gnafld.net/def/gnaf#MotorwayStreet', 'Motorway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GATEWAY', 'http://gnafld.net/def/gnaf#GatewayStreet', 'Gateway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GWY', 'http://gnafld.net/def/gnaf#GatewayStreet', 'Gateway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TRIANGLE', 'http://gnafld.net/def/gnaf#TriangleStreet', 'Triangle');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CROSSING', 'http://gnafld.net/def/gnaf#CrossingStreet', 'Crossing');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CRSG', 'http://gnafld.net/def/gnaf#CrossingStreet', 'Crossing');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HIKE', 'http://gnafld.net/def/gnaf#HikeStreet', 'Hike');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HUB', 'http://gnafld.net/def/gnaf#HubStreet', 'Hub');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TOP', 'http://gnafld.net/def/gnaf#TopStreet', 'Top');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LYNNE', 'http://gnafld.net/def/gnaf#LynneStreet', 'Lynne');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LYNN', 'http://gnafld.net/def/gnaf#LynneStreet', 'Lynne');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PATH', 'http://gnafld.net/def/gnaf#PathStreet', 'Path');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SHUN', 'http://gnafld.net/def/gnaf#ShuntStreet', 'Shunt');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SHUNT', 'http://gnafld.net/def/gnaf#ShuntStreet', 'Shunt');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DEVIATION', 'http://gnafld.net/def/gnaf#DeviationStreet', 'Deviation');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DE', 'http://gnafld.net/def/gnaf#DeviationStreet', 'Deviation');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CT', 'http://gnafld.net/def/gnaf#CourtStreet', 'Court');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'COURT', 'http://gnafld.net/def/gnaf#CourtStreet', 'Court');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CLR', 'http://gnafld.net/def/gnaf#ClusterStreet', 'Cluster');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CLUSTER', 'http://gnafld.net/def/gnaf#ClusterStreet', 'Cluster');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CCT', 'http://gnafld.net/def/gnaf#CircuitStreet', 'Circuit');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CIRCUIT', 'http://gnafld.net/def/gnaf#CircuitStreet', 'Circuit');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FSHR', 'http://gnafld.net/def/gnaf#ForeshoreStreet', 'Foreshore');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FORESHORE', 'http://gnafld.net/def/gnaf#ForeshoreStreet', 'Foreshore');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HIGHWAY', 'http://gnafld.net/def/gnaf#HighwayStreet', 'Highway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HWY', 'http://gnafld.net/def/gnaf#HighwayStreet', 'Highway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PROMENADE', 'http://gnafld.net/def/gnaf#PromenadeStreet', 'Promenade');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PROM', 'http://gnafld.net/def/gnaf#PromenadeStreet', 'Promenade');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RCH', 'http://gnafld.net/def/gnaf#ReachStreet', 'Reach');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'REACH', 'http://gnafld.net/def/gnaf#ReachStreet', 'Reach');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'THOROUGHFARE', 'http://gnafld.net/def/gnaf#ThoroughfareStreet', 'Thoroughfare');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'THFR', 'http://gnafld.net/def/gnaf#ThoroughfareStreet', 'Thoroughfare');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RDWY', 'http://gnafld.net/def/gnaf#RoadwayStreet', 'Roadway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ROADWAY', 'http://gnafld.net/def/gnaf#RoadwayStreet', 'Roadway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RAMP', 'http://gnafld.net/def/gnaf#RampStreet', 'Ramp');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RAMP', 'http://gnafld.net/def/gnaf#RampStreet', 'Ramp');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ROW', 'http://gnafld.net/def/gnaf#RowStreet', 'Row');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VILLAS', 'http://gnafld.net/def/gnaf#VillasStreet', 'Villas');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VLLS', 'http://gnafld.net/def/gnaf#VillasStreet', 'Villas');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'EAST', 'http://gnafld.net/def/gnaf#EastStreet', 'East');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WEST', 'http://gnafld.net/def/gnaf#WestStreet', 'West');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MEWS', 'http://gnafld.net/def/gnaf#MewsStreet', 'Mews');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LINE', 'http://gnafld.net/def/gnaf#LineStreet', 'Line');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BR', 'http://gnafld.net/def/gnaf#BraceStreet', 'Brace');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BRACE', 'http://gnafld.net/def/gnaf#BraceStreet', 'Brace');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CRST', 'http://gnafld.net/def/gnaf#CrestStreet', 'Crest');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CREST', 'http://gnafld.net/def/gnaf#CrestStreet', 'Crest');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RIDE', 'http://gnafld.net/def/gnaf#RideStreet', 'Ride');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RIDE', 'http://gnafld.net/def/gnaf#RideStreet', 'Ride');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ROUTE', 'http://gnafld.net/def/gnaf#RouteStreet', 'Route');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RTE', 'http://gnafld.net/def/gnaf#RouteStreet', 'Route');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DSTR', 'http://gnafld.net/def/gnaf#DistributorStreet', 'Distributor');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DISTRIBUTOR', 'http://gnafld.net/def/gnaf#DistributorStreet', 'Distributor');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CNWY', 'http://gnafld.net/def/gnaf#CentrewayStreet', 'Centreway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CENTREWAY', 'http://gnafld.net/def/gnaf#CentrewayStreet', 'Centreway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TKWY', 'http://gnafld.net/def/gnaf#TrunkwayStreet', 'Trunkway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TRUNKWAY', 'http://gnafld.net/def/gnaf#TrunkwayStreet', 'Trunkway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BANK', 'http://gnafld.net/def/gnaf#BankStreet', 'Bank');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DENE', 'http://gnafld.net/def/gnaf#DeneStreet', 'Dene');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RES', 'http://gnafld.net/def/gnaf#ReserveStreet', 'Reserve');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RESERVE', 'http://gnafld.net/def/gnaf#ReserveStreet', 'Reserve');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'THRU', 'http://gnafld.net/def/gnaf#ThroughwayStreet', 'Throughway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'THROUGHWAY', 'http://gnafld.net/def/gnaf#ThroughwayStreet', 'Throughway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'EXTENSION', 'http://gnafld.net/def/gnaf#ExtensionStreet', 'Extension');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'EXTN', 'http://gnafld.net/def/gnaf#ExtensionStreet', 'Extension');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CRIEF', 'http://gnafld.net/def/gnaf#CriefStreet', 'Crief');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CRF', 'http://gnafld.net/def/gnaf#CriefStreet', 'Crief');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'QUAYS', 'http://gnafld.net/def/gnaf#QuaysStreet', 'Quays');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'QYS', 'http://gnafld.net/def/gnaf#QuaysStreet', 'Quays');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'INTG', 'http://gnafld.net/def/gnaf#InterchangeStreet', 'Interchange');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'INTERCHANGE', 'http://gnafld.net/def/gnaf#InterchangeStreet', 'Interchange');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RAMBLE', 'http://gnafld.net/def/gnaf#RambleStreet', 'Ramble');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RMBL', 'http://gnafld.net/def/gnaf#RambleStreet', 'Ramble');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DIP', 'http://gnafld.net/def/gnaf#DipStreet', 'Dip');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'OUTLOOK', 'http://gnafld.net/def/gnaf#OutlookStreet', 'Outlook');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'OTLK', 'http://gnafld.net/def/gnaf#OutlookStreet', 'Outlook');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PRECINCT', 'http://gnafld.net/def/gnaf#PrecinctStreet', 'Precinct');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PREC', 'http://gnafld.net/def/gnaf#PrecinctStreet', 'Precinct');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MZ', 'http://gnafld.net/def/gnaf#MazeStreet', 'Maze');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MAZE', 'http://gnafld.net/def/gnaf#MazeStreet', 'Maze');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VUE', 'http://gnafld.net/def/gnaf#VueStreet', 'Vue');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HIGHROAD', 'http://gnafld.net/def/gnaf#HighroadStreet', 'Highroad');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HIRD', 'http://gnafld.net/def/gnaf#HighroadStreet', 'Highroad');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PARK', 'http://gnafld.net/def/gnaf#ParkStreet', 'Park');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PATHWAY', 'http://gnafld.net/def/gnaf#PathwayStreet', 'Pathway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PWAY', 'http://gnafld.net/def/gnaf#PathwayStreet', 'Pathway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CENTRE', 'http://gnafld.net/def/gnaf#CentreStreet', 'Centre');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CTR', 'http://gnafld.net/def/gnaf#CentreStreet', 'Centre');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'QUAD', 'http://gnafld.net/def/gnaf#QuadStreet', 'Quad');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WTWY', 'http://gnafld.net/def/gnaf#WaterwayStreet', 'Waterway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WATERWAY', 'http://gnafld.net/def/gnaf#WaterwayStreet', 'Waterway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FIREBREAK', 'http://gnafld.net/def/gnaf#FirebreakStreet', 'Firebreak');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FBRK', 'http://gnafld.net/def/gnaf#FirebreakStreet', 'Firebreak');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FIRETRACK', 'http://gnafld.net/def/gnaf#FiretrackStreet', 'Firetrack');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FTRK', 'http://gnafld.net/def/gnaf#FiretrackStreet', 'Firetrack');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BULL', 'http://gnafld.net/def/gnaf#BullStreet', 'Bull');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SBWY', 'http://gnafld.net/def/gnaf#SubwayStreet', 'Subway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SUBWAY', 'http://gnafld.net/def/gnaf#SubwayStreet', 'Subway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FIRELINE', 'http://gnafld.net/def/gnaf#FirelineStreet', 'Fireline');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FLNE', 'http://gnafld.net/def/gnaf#FirelineStreet', 'Fireline');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CONNECTION', 'http://gnafld.net/def/gnaf#ConnectionStreet', 'Connection');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CNTN', 'http://gnafld.net/def/gnaf#ConnectionStreet', 'Connection');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'AV', 'http://gnafld.net/def/gnaf#AvenueStreet', 'Avenue');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'AVENUE', 'http://gnafld.net/def/gnaf#AvenueStreet', 'Avenue');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'COMMONS', 'http://gnafld.net/def/gnaf#CommonsStreet', 'Commons');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CMMNS', 'http://gnafld.net/def/gnaf#CommonsStreet', 'Commons');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DIV', 'http://gnafld.net/def/gnaf#DivideStreet', 'Divide');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DIVIDE', 'http://gnafld.net/def/gnaf#DivideStreet', 'Divide');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MILE', 'http://gnafld.net/def/gnaf#MileStreet', 'Mile');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ENTRANCE', 'http://gnafld.net/def/gnaf#EntranceStreet', 'Entrance');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ENT', 'http://gnafld.net/def/gnaf#EntranceStreet', 'Entrance');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CLT', 'http://gnafld.net/def/gnaf#CircletStreet', 'Circlet');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CIRCLET', 'http://gnafld.net/def/gnaf#CircletStreet', 'Circlet');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GLEN', 'http://gnafld.net/def/gnaf#GlenStreet', 'Glen');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'AIRWALK', 'http://gnafld.net/def/gnaf#AirwalkStreet', 'Airwalk');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'AWLK', 'http://gnafld.net/def/gnaf#AirwalkStreet', 'Airwalk');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SERVICEWAY', 'http://gnafld.net/def/gnaf#ServicewayStreet', 'Serviceway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SVWY', 'http://gnafld.net/def/gnaf#ServicewayStreet', 'Serviceway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BDWY', 'http://gnafld.net/def/gnaf#BroadwayStreet', 'Broadway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BROADWAY', 'http://gnafld.net/def/gnaf#BroadwayStreet', 'Broadway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FORM', 'http://gnafld.net/def/gnaf#FormationStreet', 'Formation');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FORMATION', 'http://gnafld.net/def/gnaf#FormationStreet', 'Formation');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'UPAS', 'http://gnafld.net/def/gnaf#UnderpassStreet', 'Underpass');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'UNDERPASS', 'http://gnafld.net/def/gnaf#UnderpassStreet', 'Underpass');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RIDGE', 'http://gnafld.net/def/gnaf#RidgeStreet', 'Ridge');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RDGE', 'http://gnafld.net/def/gnaf#RidgeStreet', 'Ridge');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TRAMWAY', 'http://gnafld.net/def/gnaf#TramwayStreet', 'Tramway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TMWY', 'http://gnafld.net/def/gnaf#TramwayStreet', 'Tramway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FLATS', 'http://gnafld.net/def/gnaf#FlatsStreet', 'Flats');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FLTS', 'http://gnafld.net/def/gnaf#FlatsStreet', 'Flats');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FRONTAGE', 'http://gnafld.net/def/gnaf#FrontageStreet', 'Frontage');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FRTG', 'http://gnafld.net/def/gnaf#FrontageStreet', 'Frontage');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PNT', 'http://gnafld.net/def/gnaf#PointStreet', 'Point');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'POINT', 'http://gnafld.net/def/gnaf#PointStreet', 'Point');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WHRF', 'http://gnafld.net/def/gnaf#WharfStreet', 'Wharf');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WHARF', 'http://gnafld.net/def/gnaf#WharfStreet', 'Wharf');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HRBR', 'http://gnafld.net/def/gnaf#HarbourStreet', 'Harbour');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HARBOUR', 'http://gnafld.net/def/gnaf#HarbourStreet', 'Harbour');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BYWAY', 'http://gnafld.net/def/gnaf#BywayStreet', 'Byway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BYWY', 'http://gnafld.net/def/gnaf#BywayStreet', 'Byway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'STRAND', 'http://gnafld.net/def/gnaf#StrandStreet', 'Strand');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'STRA', 'http://gnafld.net/def/gnaf#StrandStreet', 'Strand');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FOOTWAY', 'http://gnafld.net/def/gnaf#FootwayStreet', 'Footway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FTWY', 'http://gnafld.net/def/gnaf#FootwayStreet', 'Footway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VIADUCT', 'http://gnafld.net/def/gnaf#ViaductStreet', 'Viaduct');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VIAD', 'http://gnafld.net/def/gnaf#ViaductStreet', 'Viaduct');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ESTATE', 'http://gnafld.net/def/gnaf#EstateStreet', 'Estate');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'EST', 'http://gnafld.net/def/gnaf#EstateStreet', 'Estate');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DALE', 'http://gnafld.net/def/gnaf#DaleStreet', 'Dale');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LKT', 'http://gnafld.net/def/gnaf#LookoutStreet', 'Lookout');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LOOKOUT', 'http://gnafld.net/def/gnaf#LookoutStreet', 'Lookout');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TERRACE', 'http://gnafld.net/def/gnaf#TerraceStreet', 'Terrace');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TCE', 'http://gnafld.net/def/gnaf#TerraceStreet', 'Terrace');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WDS', 'http://gnafld.net/def/gnaf#WoodsStreet', 'Woods');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WOODS', 'http://gnafld.net/def/gnaf#WoodsStreet', 'Woods');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'KEYS', 'http://gnafld.net/def/gnaf#KeysStreet', 'Keys');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BRK', 'http://gnafld.net/def/gnaf#BreakStreet', 'Break');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BREAK', 'http://gnafld.net/def/gnaf#BreakStreet', 'Break');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'STRP', 'http://gnafld.net/def/gnaf#StripStreet', 'Strip');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'STRIP', 'http://gnafld.net/def/gnaf#StripStreet', 'Strip');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RDS', 'http://gnafld.net/def/gnaf#RoadsStreet', 'Roads');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ROADS', 'http://gnafld.net/def/gnaf#RoadsStreet', 'Roads');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RIVER', 'http://gnafld.net/def/gnaf#RiverStreet', 'River');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RVR', 'http://gnafld.net/def/gnaf#RiverStreet', 'River');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FORK', 'http://gnafld.net/def/gnaf#ForkStreet', 'Fork');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FORK', 'http://gnafld.net/def/gnaf#ForkStreet', 'Fork');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LOOP', 'http://gnafld.net/def/gnaf#LoopStreet', 'Loop');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TRAIL', 'http://gnafld.net/def/gnaf#TrailStreet', 'Trail');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TRL', 'http://gnafld.net/def/gnaf#TrailStreet', 'Trail');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TUNNEL', 'http://gnafld.net/def/gnaf#TunnelStreet', 'Tunnel');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TUNL', 'http://gnafld.net/def/gnaf#TunnelStreet', 'Tunnel');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PWY', 'http://gnafld.net/def/gnaf#ParkwayStreet', 'Parkway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PARKWAY', 'http://gnafld.net/def/gnaf#ParkwayStreet', 'Parkway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'INLT', 'http://gnafld.net/def/gnaf#InletStreet', 'Inlet');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'INLET', 'http://gnafld.net/def/gnaf#InletStreet', 'Inlet');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'YARD', 'http://gnafld.net/def/gnaf#YardStreet', 'Yard');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RETURN', 'http://gnafld.net/def/gnaf#ReturnStreet', 'Return');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RTN', 'http://gnafld.net/def/gnaf#ReturnStreet', 'Return');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BRIDGE', 'http://gnafld.net/def/gnaf#BridgeStreet', 'Bridge');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BDGE', 'http://gnafld.net/def/gnaf#BridgeStreet', 'Bridge');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FAIRWAY', 'http://gnafld.net/def/gnaf#FairwayStreet', 'Fairway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FAWY', 'http://gnafld.net/def/gnaf#FairwayStreet', 'Fairway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CRCS', 'http://gnafld.net/def/gnaf#CircusStreet', 'Circus');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CIRCUS', 'http://gnafld.net/def/gnaf#CircusStreet', 'Circus');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'NULL', 'http://gnafld.net/def/gnaf#NullStreet', 'Null');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'REST', 'http://gnafld.net/def/gnaf#RestStreet', 'Rest');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TOLLWAY', 'http://gnafld.net/def/gnaf#TollwayStreet', 'Tollway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TLWY', 'http://gnafld.net/def/gnaf#TollwayStreet', 'Tollway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'AMBL', 'http://gnafld.net/def/gnaf#AmbleStreet', 'Amble');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'AMBLE', 'http://gnafld.net/def/gnaf#AmbleStreet', 'Amble');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BVDE', 'http://gnafld.net/def/gnaf#BoulevardeStreet', 'Boulevarde');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BOULEVARDE', 'http://gnafld.net/def/gnaf#BoulevardeStreet', 'Boulevarde');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FRONT', 'http://gnafld.net/def/gnaf#FrontStreet', 'Front');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FRNT', 'http://gnafld.net/def/gnaf#FrontStreet', 'Front');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LANDING', 'http://gnafld.net/def/gnaf#LandingStreet', 'Landing');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LDG', 'http://gnafld.net/def/gnaf#LandingStreet', 'Landing');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CSWY', 'http://gnafld.net/def/gnaf#CausewayStreet', 'Causeway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CAUSEWAY', 'http://gnafld.net/def/gnaf#CausewayStreet', 'Causeway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LNWY', 'http://gnafld.net/def/gnaf#LanewayStreet', 'Laneway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LANEWAY', 'http://gnafld.net/def/gnaf#LanewayStreet', 'Laneway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HEATH', 'http://gnafld.net/def/gnaf#HeathStreet', 'Heath');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'HTH', 'http://gnafld.net/def/gnaf#HeathStreet', 'Heath');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'COURSE', 'http://gnafld.net/def/gnaf#CourseStreet', 'Course');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CRSE', 'http://gnafld.net/def/gnaf#CourseStreet', 'Course');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'STRAIGHT', 'http://gnafld.net/def/gnaf#StraightStreet', 'Straight');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'STRT', 'http://gnafld.net/def/gnaf#StraightStreet', 'Straight');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BEND', 'http://gnafld.net/def/gnaf#BendStreet', 'Bend');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PLACE', 'http://gnafld.net/def/gnaf#PlaceStreet', 'Place');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PL', 'http://gnafld.net/def/gnaf#PlaceStreet', 'Place');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VWS', 'http://gnafld.net/def/gnaf#ViewsStreet', 'Views');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'VIEWS', 'http://gnafld.net/def/gnaf#ViewsStreet', 'Views');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WATERS', 'http://gnafld.net/def/gnaf#WatersStreet', 'Waters');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WTRS', 'http://gnafld.net/def/gnaf#WatersStreet', 'Waters');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PASSAGE', 'http://gnafld.net/def/gnaf#PassageStreet', 'Passage');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PSGE', 'http://gnafld.net/def/gnaf#PassageStreet', 'Passage');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MANOR', 'http://gnafld.net/def/gnaf#ManorStreet', 'Manor');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MANR', 'http://gnafld.net/def/gnaf#ManorStreet', 'Manor');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RIGHT OF WAY', 'http://gnafld.net/def/gnaf#RightOfWayStreet', 'Right Of Way');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ROFW', 'http://gnafld.net/def/gnaf#RightOfWayStreet', 'Right Of Way');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SPUR', 'http://gnafld.net/def/gnaf#SpurStreet', 'Spur');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SPUR', 'http://gnafld.net/def/gnaf#SpurStreet', 'Spur');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BCH', 'http://gnafld.net/def/gnaf#BeachStreet', 'Beach');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'BEACH', 'http://gnafld.net/def/gnaf#BeachStreet', 'Beach');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LEDR', 'http://gnafld.net/def/gnaf#LeaderStreet', 'Leader');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'LEADER', 'http://gnafld.net/def/gnaf#LeaderStreet', 'Leader');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ALLEYWAY', 'http://gnafld.net/def/gnaf#AlleywayStreet', 'Alleyway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ALWY', 'http://gnafld.net/def/gnaf#AlleywayStreet', 'Alleyway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FORD', 'http://gnafld.net/def/gnaf#FordStreet', 'Ford');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WALK', 'http://gnafld.net/def/gnaf#WalkStreet', 'Walk');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ARC', 'http://gnafld.net/def/gnaf#ArcadeStreet', 'Arcade');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'ARCADE', 'http://gnafld.net/def/gnaf#ArcadeStreet', 'Arcade');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'DOWN', 'http://gnafld.net/def/gnaf#DownStreet', 'Down');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CNCD', 'http://gnafld.net/def/gnaf#ConcordStreet', 'Concord');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CONCORD', 'http://gnafld.net/def/gnaf#ConcordStreet', 'Concord');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CIRCLE', 'http://gnafld.net/def/gnaf#CircleStreet', 'Circle');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'CIR', 'http://gnafld.net/def/gnaf#CircleStreet', 'Circle');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GARDENS', 'http://gnafld.net/def/gnaf#GardensStreet', 'Gardens');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GDNS', 'http://gnafld.net/def/gnaf#GardensStreet', 'Gardens');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RISING', 'http://gnafld.net/def/gnaf#RisingStreet', 'Rising');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'RSNG', 'http://gnafld.net/def/gnaf#RisingStreet', 'Rising');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'WADE', 'http://gnafld.net/def/gnaf#WadeStreet', 'Wade');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'JUNCTION', 'http://gnafld.net/def/gnaf#JunctionStreet', 'Junction');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'JNC', 'http://gnafld.net/def/gnaf#JunctionStreet', 'Junction');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'STEPS', 'http://gnafld.net/def/gnaf#StepsStreet', 'Steps');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'STPS', 'http://gnafld.net/def/gnaf#StepsStreet', 'Steps');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PIAZZA', 'http://gnafld.net/def/gnaf#PiazzaStreet', 'Piazza');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PIAZ', 'http://gnafld.net/def/gnaf#PiazzaStreet', 'Piazza');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PLAZA', 'http://gnafld.net/def/gnaf#PlazaStreet', 'Plaza');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'PLZA', 'http://gnafld.net/def/gnaf#PlazaStreet', 'Plaza');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'FLAT', 'http://gnafld.net/def/gnaf#FlatStreet', 'Flat');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GLY', 'http://gnafld.net/def/gnaf#GullyStreet', 'Gully');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'GULLY', 'http://gnafld.net/def/gnaf#GullyStreet', 'Gully');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'MEW', 'http://gnafld.net/def/gnaf#MewStreet', 'Mew');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'EXPRESSWAY', 'http://gnafld.net/def/gnaf#ExpresswayStreet', 'Expressway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'EXP', 'http://gnafld.net/def/gnaf#ExpresswayStreet', 'Expressway');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'KEY', 'http://gnafld.net/def/gnaf#KeyStreet', 'Key');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'NORTH', 'http://gnafld.net/def/gnaf#NorthStreet', 'North');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'NTH', 'http://gnafld.net/def/gnaf#NorthStreet', 'North');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SLOPE', 'http://gnafld.net/def/gnaf#SlopeStreet', 'Slope');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'SLPE', 'http://gnafld.net/def/gnaf#SlopeStreet', 'Slope');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'TARN', 'http://gnafld.net/def/gnaf#TarnStreet', 'Tarn');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Street', 'EDGE', 'http://gnafld.net/def/gnaf#EdgeStreet', 'Edge');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('MeshBlockMatch', '1', 'http://gnafld.net/def/gnaf#ParcelLevelMatch', 'Parcel Level Match');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('MeshBlockMatch', '2', 'http://gnafld.net/def/gnaf#GapGeocodedAddressLevelMatch', 'Gap Geocoded Address Level Match');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('MeshBlockMatch', '5', 'http://gnafld.net/def/gnaf#LocalityLevelSingleMatch', 'Locality Level Single Match');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('MeshBlockMatch', '3', 'http://gnafld.net/def/gnaf#StreetLocalityLevelSingleMatch', 'Street Locality Level Single Match');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('MeshBlockMatch', '4', 'http://gnafld.net/def/gnaf#StreetLocalityLevelMultipleMatch', 'Street Locality Level Multiple Match');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Alias', 'AL', 'http://gnafld.net/def/gnaf#AlternativeLocalityAlias', 'Alternative Locality Alias');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Alias', '', 'http://gnafld.net/def/gnaf#StreetLocalityAlias', 'Street Locality Alias');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Alias', 'CD', 'http://gnafld.net/def/gnaf#ContributorDefinedAlias', 'Contributor Defined Alias');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Alias', 'RA', 'http://gnafld.net/def/gnaf#RangedAddressAlias', 'Ranged Address Alias');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Alias', '', 'http://gnafld.net/def/gnaf#LocalityAlias', 'Locality Alias');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Alias', 'ALT', 'http://gnafld.net/def/gnaf#AlternativeAlias', 'Alternative Alias');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Alias', 'FNNFS', 'http://gnafld.net/def/gnaf#FlatNumberNoFirstSuffixCorrelationAlias', 'Flat Number – No First Suffix Correlation Alias');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Alias', 'SYN', 'http://gnafld.net/def/gnaf#SynonymAlias', 'Synonym Alias');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Alias', 'MR', 'http://gnafld.net/def/gnaf#MaintenanceReferenceAlias', 'Maintenance Reference Alias');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Alias', 'SR', 'http://gnafld.net/def/gnaf#SpatiallyRelatedAlias', 'Spatially Related Alias');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Alias', 'LD', 'http://gnafld.net/def/gnaf#LevelDuplicationAlias', 'Level Duplication Alias');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/ROOM', 'http://gnafld.net/def/gnaf#UnknownRoomAddress', 'Unknown Room Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/REAR', 'http://gnafld.net/def/gnaf#UnknownRearAddress', 'Unknown Rear Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R/SITE', 'http://gnafld.net/def/gnaf#RuralSiteAddress', 'Rural Site Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/LOT', 'http://gnafld.net/def/gnaf#UnknownLotAddress', 'Unknown Lot Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R/CABIN', 'http://gnafld.net/def/gnaf#RuralCabinAddress', 'Rural Cabin Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R/FLAT', 'http://gnafld.net/def/gnaf#RuralFlatAddress', 'Rural Flat Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/SITE', 'http://gnafld.net/def/gnaf#UnknownSiteAddress', 'Unknown Site Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/RES', 'http://gnafld.net/def/gnaf#UnknownReserveAddress', 'Unknown Reserve Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R/UNIT', 'http://gnafld.net/def/gnaf#RuralUnitAddress', 'Rural Unit Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/RMB', 'http://gnafld.net/def/gnaf#UrbanRoadsideMailBoxAddress', 'Urban Roadside Mail Box Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/TNHS', 'http://gnafld.net/def/gnaf#UnknownTownhouseAddress', 'Unknown Townhouse Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN', 'http://gnafld.net/def/gnaf#UnknownVillaAddress', 'Unknown Villa Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/RMB', 'http://gnafld.net/def/gnaf#UnknownRoadsideMailBoxAddress', 'Unknown Roadside Mail Box Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R/ROOM', 'http://gnafld.net/def/gnaf#RuralRoomAddress', 'Rural Room Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/PTHS', 'http://gnafld.net/def/gnaf#UnknownPenthouseAddress', 'Unknown Penthouse Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/APT', 'http://gnafld.net/def/gnaf#UnknownApartmentAddress', 'Unknown Apartment Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/BLOCK', 'http://gnafld.net/def/gnaf#UrbanBlockAddress', 'Urban Block Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/RSD', 'http://gnafld.net/def/gnaf#UrbanRoadsideMailDeliveryAddress', 'Urban Roadside Mail Delivery Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/CTGE', 'http://gnafld.net/def/gnaf#UnknownCottageAddress', 'Unknown Cottage Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/', 'http://gnafld.net/def/gnaf#UnknownAddress', 'Unknown Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/SEC', 'http://gnafld.net/def/gnaf#UnknownSectionAddress', 'Unknown Section Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/UNIT', 'http://gnafld.net/def/gnaf#UnknownUnitAddress', 'Unknown Unit Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R/HOUSE', 'http://gnafld.net/def/gnaf#RuralHouseAddress', 'Rural House Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R/SEC', 'http://gnafld.net/def/gnaf#RuralSectionAddress', 'Rural Section Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/CABIN', 'http://gnafld.net/def/gnaf#UnknownCabinAddress', 'Unknown Cabin Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/HOUSE', 'http://gnafld.net/def/gnaf#UnknownHouseAddress', 'Unknown House Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/RMS', 'http://gnafld.net/def/gnaf#UrbanRoadsideMailServiceAddress', 'Urban Roadside Mail Service Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/RSM', 'http://gnafld.net/def/gnaf#UrbanRoadsideMailServiceAddress', 'Urban Roadside Mail Service Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/SEC', 'http://gnafld.net/def/gnaf#UrbanSectionAddress', 'Urban Section Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/SITE', 'http://gnafld.net/def/gnaf#UrbanSiteAddress', 'Urban Site Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/LWR', 'http://gnafld.net/def/gnaf#UnknownLowerAddress', 'Unknown Lower Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/GD', 'http://gnafld.net/def/gnaf#UnknownGroundFloorAddress', 'Unknown Ground Floor Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/CVAN', 'http://gnafld.net/def/gnaf#UnknownCaravanAddress', 'Unknown Caravan Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/RES', 'http://gnafld.net/def/gnaf#UrbanReserveAddress', 'Urban Reserve Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R/RES', 'http://gnafld.net/def/gnaf#RuralReserveAddress', 'Rural Reserve Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/RMS', 'http://gnafld.net/def/gnaf#UnknownRoadsideMailMailServiceAddress', 'Unknown Roadside Mail Service Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/POR', 'http://gnafld.net/def/gnaf#UnknownPortionAddress', 'Unknown Portion Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R/LOT', 'http://gnafld.net/def/gnaf#RuralLotAddress', 'Rural Lot Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R/RSD', 'http://gnafld.net/def/gnaf#RuralRoadsideMailDeliveryAddress', 'Rural Roadside Mail Delivery Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR', 'http://gnafld.net/def/gnaf#UrbanAddress', 'Urban Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/LOT', 'http://gnafld.net/def/gnaf#UrbanLotAddress', 'Urban Lot Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/RSM', 'http://gnafld.net/def/gnaf#UnknownRoadsideMailService2Address', 'Unknown Roadside Mail Box Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R/BLOCK', 'http://gnafld.net/def/gnaf#RuralBlockAddress', 'Rural Block Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R', 'http://gnafld.net/def/gnaf#RuralAddress', 'Rural Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R/RMB', 'http://gnafld.net/def/gnaf#RuralRoadsideMailBoxAddress', 'Rural Roadside Mail Box Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/FLAT', 'http://gnafld.net/def/gnaf#UnknownFlatAddress', 'Unknown Flat Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/HOUSE', 'http://gnafld.net/def/gnaf#UrbanHouseAddress', 'Urban House Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/ROOM', 'http://gnafld.net/def/gnaf#UrbanRoomAddress', 'Urban Room Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/BLOCK', 'http://gnafld.net/def/gnaf#UnknownBlockAddress', 'Unknown Block Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/FLAT', 'http://gnafld.net/def/gnaf#UrbanFlatAddress', 'Urban Flat Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/UNIT', 'http://gnafld.net/def/gnaf#UrbanUnitAddress', 'Urban Unit Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UR/CABIN', 'http://gnafld.net/def/gnaf#UrbanCabinAddress', 'Urban Cabin Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'R/RSM', 'http://gnafld.net/def/gnaf#RuralRoadsideMailServiceAddress', 'Rural Roadside Mail Service Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/FARM', 'http://gnafld.net/def/gnaf#UnknownFarmAddress', 'Unknown Farm Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/LOC', 'http://gnafld.net/def/gnaf#UnknownLocationAddress', 'Unknown Location Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Address', 'UN/RSD', 'http://gnafld.net/def/gnaf#UnknownRoadsideMailDeliveryAddress', 'Unknown Roadside Mail Delivery Address');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('MeshBlock', '2011', 'http://gnafld.net/def/gnaf#2011MB', '2011 Mesh Block');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('MeshBlock', '2016', 'http://gnafld.net/def/gnaf#2016MB', '2016 Mesh Block');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('PrimarySecondaryJoin', '1', 'http://gnafld.net/def/gnaf#AutoPrimarySecondaryJoin', 'Auto');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('PrimarySecondaryJoin', '2', 'http://gnafld.net/def/gnaf#ManualPrimarySecondaryJoin', 'Manual');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'PAP', 'http://gnafld.net/def/gnaf#PropertyAccessPointGeocode', 'Property Access Point');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'BC', 'http://gnafld.net/def/gnaf#BuildingCentroidGeocode', 'Building Centroid');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'EA', 'http://gnafld.net/def/gnaf#EmergencyAccessGeocode', 'Emergency Access');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'ICP', 'http://gnafld.net/def/gnaf#InternetConnectionPointGeocode', 'Internet Connection Point');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'FDA', 'http://gnafld.net/def/gnaf#FrontDoorAccessGeocode', 'Front Door Access');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'PCM', 'http://gnafld.net/def/gnaf#PropertyCentroidManualGeocode', 'Property Centroid Manual');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'LOC', 'http://gnafld.net/def/gnaf#LocalityGeocode', 'Locality');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'LB', 'http://gnafld.net/def/gnaf#LetterboxGeocode', 'Letterbox');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'EM', 'http://gnafld.net/def/gnaf#ElectricityMeterPointGeocode', 'Electricity Meter Point');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'FC', 'http://gnafld.net/def/gnaf#FrontageCentreGeocode', 'Frontage Centre');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'PAPS', 'http://gnafld.net/def/gnaf#PropertyAccessPointSetbackGeocode', 'Property Access Point Setback');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'BAP', 'http://gnafld.net/def/gnaf#BuildingAccessPointGeocode', 'Building Access Point');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'EAS', 'http://gnafld.net/def/gnaf#EmergencyAccessSecondaryGeocode', 'Emergency Access Secondary');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'WM', 'http://gnafld.net/def/gnaf#WaterMeterGeocode', 'Water Meter');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'GG', 'http://gnafld.net/def/gnaf#GapGeocode', 'Gap Geocode');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'ECP', 'http://gnafld.net/def/gnaf#ElectricityConnectionPointGeocode', 'Electricity Connection Point');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'CDF', 'http://gnafld.net/def/gnaf#CentreLineDroppedFrontageGeocode', 'Centre-Line Dropped Frontage');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'FCS', 'http://gnafld.net/def/gnaf#FrontageCentreSetbackGeocode', 'Frontage Centre Setback');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'WCP', 'http://gnafld.net/def/gnaf#WaterConnectionPointGeocode', 'Water Connection Point');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'STL', 'http://gnafld.net/def/gnaf#StreetLocalityGeocode', 'Street Locality');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'PC', 'http://gnafld.net/def/gnaf#PropertyCentroidGeocode', 'Property Centroid');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'TCP', 'http://gnafld.net/def/gnaf#TelephoneConnectionPointGeocode', 'Telephone Connection Point');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'SCP', 'http://gnafld.net/def/gnaf#SewageConnectionPointGeocode', 'Sewage Connection Point');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'UC', 'http://gnafld.net/def/gnaf#UnitCentroidGeocode', 'Unit Centroid');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'DF', 'http://gnafld.net/def/gnaf#DrivewayFrontageGeocode', 'Driveway Frontage');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'UNK', 'http://gnafld.net/def/gnaf#UnknownGeocode', 'Unknown');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'UCM', 'http://gnafld.net/def/gnaf#UnitCentroidManualGeocode', 'Unit Centroid Manual');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'GCP', 'http://gnafld.net/def/gnaf#GasConnectionPointGeocode', 'Gas Connection Point');
INSERT INTO code_uris (vocab, code, uri, prefLabel) VALUES ('Geocode', 'GM', 'http://gnafld.net/def/gnaf#GasMeterPointGeocode', 'Gas Meter Point');